[tool.poetry]
name = "SmudgeLord"
version = "0.1.0"
description = ""
authors = ["ruizlenato <ruizlenato@proton.me>"]
license = "GPL-3.0"
readme = "README.rst"

[tool.poetry.dependencies]
python = "^3.10"
pyrogram = {git = "https://github.com/AmanoTeam/pyrogram.git"}
TgCrypto = "^1.2.5"
uvloop = "^0.17.0"
aiosqlite = "^0.19.0"
pyyaml = "^6.0"

[tool.poetry.group.dev.dependencies]
black = "^23.3.0"
isort = "^5.12.0"
pybabel = "^0.0.0.dev0"

[tool.isort]
profile = "black"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
